Ammo.Portal/Controllers/BulletCollectionController.cs
using Ammo.Domain.Entities;
using Ammo.Domain.Services.Abstract;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ammo.Portal.Controllers
{
    [Authorize]
    [RoutePrefix("BulletCollection")]
    public class BulletCollectionController : BaseController
    {
        private IBulletCollectionService _collectionService;

        public BulletCollectionController(IBulletCollectionService collectionService)
        {
            _collectionService = collectionService;
        }

        [Route("List")]
        public ActionResult List()
        {
            IEnumerable<BulletCollection> model = _collectionService.GetByUser(User.Identity.GetUserId());

            return PartialView("_List", model);
        }

        [Route("SelectList/{JournalId}")]
        public ActionResult SelectList(int JournalId)
        {
            IEnumerable<BulletCollection> collections = _collectionService.GetByUser(User.Identity.GetUserId());
            JournalBulletCollection model = new JournalBulletCollection()
            {
                JournalId = JournalId,
                Collections = collections
            };

            return PartialView("_SelectList", model);
        }
    }
}

Ammo.Portal/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ammo.Portal.Controllers
{
    // TODO Make the paths config!
    public class ImageController : BaseController
    {
        [HttpGet]
        public ActionResult Get(string fileName)
        {
            var dir = Server.MapPath("/Media");
            var path = Path.Combine(dir, fileName + ".jpg");
            return base.File(path, "image/jpeg");
        }

        [HttpGet]
        public FileResult DefaultCoverGet()
        {
            string path = Server.MapPath("/Assets/images/backgrounds/blank-cover.png");

            return new FileStreamResult(new FileStream(path, FileMode.Open), "image/png");
        }

        [HttpGet]
        [Authorize]
        public FileResult JournalCoverGet(string ImageName = null)
        {
            if(string.IsNullOrEmpty(ImageName))
            {
                return DefaultCoverGet();
            }
            else
            {
                string path = Server.MapPath(string.Concat("/Media/ImageUploads/JournalCovers/", ImageName));

                return new FileStreamResult(new FileStream(path, FileMode.Open), "image/png");
            }        
        }

        [HttpGet]
        [Authorize]
        public FileResult BulletGet(string BulletUri = null)
        {
            if(string.IsNullOrEmpty(BulletUri))
            {
                return new FileStreamResult(new FileStream("/Assets/icons/bullet.png", FileMode.Open), "image/[ng");
            }
            else
            {
                string path = Server.MapPath(string.Concat("/Assets/bullets/", BulletUri));

                return new FileStreamResult(new FileStream(path, FileMode.Open), "image/png");
            }
        }
    }
}

Ammo.Portal/Controllers/JournalBulletCollectionController.cs
using Ammo.Domain.Entities;
using Ammo.Domain.Services.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Ammo.Portal.Controllers
{
    public class JournalBulletCollectionController : BaseController
    {
        IJournalBulletCollectionService _journalBulletCollectionService;

        public JournalBulletCollectionController(IJournalBulletCollectionService journalBulletCollectionService)
        {
            _journalBulletCollectionService = journalBulletCollectionService;
        }

        [Authorize]
        [Route("Save")]
        public ActionResult Save(JournalBulletCollection Collection)
        {
            if(ModelState.IsValid)
            {
                //TODO call AddUpdate

                return Json(new
                {
                    result = "Success",
                    notify = false,
                    view = ""
                }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new
                {
                    result = "Error",
                    notify = true, 
                    view = ""
                }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Ammo.Portal/Views/BulletCollection/_List.cshtml
@model IEnumerable<Ammo.Domain.Entities.BulletCollection>
@{
    Layout = null;
}
<div class="col-lg-12 col-md-12 col-sm-12">
    @if (Model != null && Model.Count() > 0)
    {
        foreach (Ammo.Domain.Entities.BulletCollection collection in Model)
        {
            <div class="col-lg-4 col-md-3 col-sm-12" id="bullet-collection-@collection.BullectCollectionId">
                <section class="bullet-collection">
                    @if(collection.Bullets != null && collection.Bullets.Count() > 0)
                    {
                        foreach (Ammo.Domain.Entities.Bullet bullet in collection.Bullets)
                        {
                            <img src="@Url.Action("BulletGet", "Image", new { BulletUri = bullet.ImageUri })" />
                        }
                    }
                </section>
                <h1>@Html.Raw(collection.Name)</h1>
            </div>
        }
    }
</div>

Ammo.Portal/Views/BulletCollection/_SelectList.cshtml
@model Ammo.Domain.Entities.JournalBulletCollection
@{
    Layout = null;
}
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
        @if (Model.Collections != null && Model.Collections.Count() > 0)
        {
            foreach (Ammo.Domain.Entities.BulletCollection collection in Model.Collections)
            {
                <div class="col-lg-@Html.Raw(12/Model.Collections.Count()) col-md-@Html.Raw(12/Model.Collections.Count()) col-sm-12 bullet-collection-div" id="bullet-collection-@collection.BulletCollectionId">
                    <section class="bullet-collection">
                        @if (collection.Bullets != null && collection.Bullets.Count() > 0)
                    {
                        foreach (Ammo.Domain.Entities.Bullet bullet in collection.Bullets)
                        {
                                <img src="@Url.Action("BulletGet", "Image", new { BulletUri = bullet.ImageUri })" />
                            }
                        }
                    </section>
                    <h3 class="bullet-collection-div-h3">@Html.Raw(collection.Name)</h3>
                    @using (Ajax.BeginForm("Save", "JournalBulletCollection", null, new AjaxOptions() { OnSuccess = "JOURNAL.OnBulletCollectionSuccess", OnFailure = "JOURNAL.OnBulletCollectionError" }, new { @id = Html.Raw(collection.BulletCollectionId) }))
                    {
                        @Html.HiddenFor(m => m.SelectedBulletCollectionId, new { @value = collection.BulletCollectionId })
                        @Html.HiddenFor(m => m.JournalId)
                        <button form="@collection.BulletCollectionId" type="submit" class="btn standard-button green-button green-outline"> USE THIS COLLECTION</button>
                    }
                </div>
            }
        }
    </div>
</div>
<div class="four-lines">
    <div class="line red-line-bottom">
    </div>
    <div class="line green-line-bottom">
    </div>
    <div class="line purple-line-bottom">
    </div>
    <div class="line yellow-line-bottom">
    </div>
</div>